version: '3.9'

services:
  db:
    image: postgres:16
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: SUPINFO2025
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - library_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: library_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app

volumes:
  library_data: {}
