"""add role to user

Revision ID: 0be69756da1c
Revises: b29d781daad7
Create Date: 2025-09-24 15:07:16.718543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be69756da1c'
down_revision: Union[str, None] = 'b29d781daad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum('admin', 'user', name='roleenum')

def upgrade() -> None:
    """Upgrade schema."""
    role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', role_enum, nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
    role_enum.drop(op.get_bind(), checkfirst=True)